default_language_version:
    python: python3.11

repos:
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black

-   repo: https://github.com/PyCQA/pylint
    rev: v2.16.2
    hooks:
    - id: pylint

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit

-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.1
    hooks:
    - id: python-safety-dependencies-check

-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0
    hooks:
    - id: gitlint
